In [ ]:
import numpy as np
import time

In [ ]:
# PROBLEM 1 – Array Creation

#Array Creation:

#1. Initialize an empty array with size 2X2.
empty_arrr = np.empty((2,2),dtype = int)
print("1. Empty Array (2x2):\n", empty_arr)

1. Empty Array (2x2):
 [[        368358342                 0]
 [28429463976178529   132625312531200]]


In [ ]:
#2 Initialize an all one array with size 4X2.
ones_arrr = np.ones((4,2))
print("\n2. Ones Array (4x2):\n", ones_arr)


2. Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#3 Return a new array of given shape and type, filled with fill value.{Hint: np.full}
full_arrr = np.full((3,3), 7)
print("\n3. Full Array (3x3 filled with 7):\n", full_arrr)


3. Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
#4 Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
sample = np.array([[5,6,7],[8,9,10]])
zero_like = np.zeros_like(sample)
print("\n4. Zeros like sample array:\n", zero_like)


4. Zeros like sample array:
 [[0 0 0]
 [0 0 0]]


In [ ]:
#5 Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
one_like = np.ones_like(sample)
print("\n5. Ones like sample array:\n", one_like)


5. Ones like sample array:
 [[1 1 1]
 [1 1 1]]


In [ ]:
#6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1,2,3,4]
numpy_arrr = np.array(new_list)
print("\n6. Converted List to Array:\n", numpy_arrr)



6. Converted List to Array:
 [1 2 3 4]


In [ ]:
#Task 2
#Array Manipulation: Numerical Ranges and Array indexing:

#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
arrr= np.arange(10, 50)
print("1. Array from 10 to 49:\n", arrr)

1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2 Create a 3X3 matrix with values ranging from 0 to 8.
arr2 = np.arange(9).reshape(3,3)
print("\n2. 3x3 Matrix 0 to 8:\n", arr2)


2. 3x3 Matrix 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#3 Create a 3X3 identity matrix.
identity = np.eye(3)
print("\n3. Identity Matrix 3x3:\n", identity)

In [ ]:
#4 Create a random array of size 30 and find the mean of the array.
rand30 = np.random.random(30)
print("\n4. Mean of random array of 30 values:", rand30.mean())



4. Mean of random array of 30 values: 0.5444060123472384


In [ ]:
#5 Create a 10X10 array with random values and find the minimum and maximum values.
rand10 = np.random.random((10,10))
print("\n5. Min:", rand10.min(), "Max:", rand10.max())


5. Min: 0.010886646931803523 Max: 0.9781061488304488


In [ ]:
#6 Create a zero array of size 10 and replace 5th element with 1.
z = np.zeros(10)
z[4] = 1
print("\n6. Zero array, 5th element set to 1:\n", z)


6. Zero array, 5th element set to 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7 Reverse an array arr = [1,2,0,0,4,0].
arr_rev = np.array([1,2,0,0,4,0])[::-1]
print("\n7. Reversed Array:\n", arr_rev)


7. Reversed Array:
 [0 4 0 0 2 1]


In [ ]:
#8. Create a 2d array with 1 on border and 0 inside.
border_arr = np.ones((5,5))
border_arr[1:-1,1:-1] = 0
print("\n8. Border 1s and inside 0s:\n", border_arr)


8. Border 1s and inside 0s:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard:\n", checker)


9. 8x8 Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Problem 3
#For the following arrays:
#x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
#v = np.array([9,10]) and w = np.array([11,12]);
#Complete all the task using numpy:

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

#1. Add the two array.
print("1. x + y:\n", np.add(x,y))

#2Subtract the two array.
print("\n2. x - y:\n", np.subtract(x,y))

#3Multiply the array with any integers of your choice.
print("\n3. x * 5:\n", x * 5)

#4Find the square of each element of the array.
print("\n4. x squared:\n", np.power(x,2))

#5 Find the dot product between: v(and)w ; x(and)v ; x(and)y.
print("\n5. v.w =", np.dot(v,w))
print("   x.v =\n", np.dot(x,v))
print("   x.y =\n", np.dot(x,y))

#6 Concatenate x(and)y along row and Concatenate v(and)w along column.
xy_row = np.concatenate((x,y), axis=0)
print("\n6. Concatenate x and y along rows:\n", xy_row)

vw_col = np.vstack((v,w))
print("\n   Concatenate v and w as rows:\n", vw_col)

#7 Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
print("\n7. x and v cannot concatenate because dimensions do not match.")


1. x + y:
 [[ 6  8]
 [10 13]]

2. x - y:
 [[-4 -4]
 [-4 -3]]

3. x * 5:
 [[ 5 10]
 [15 25]]

4. x squared:
 [[ 1  4]
 [ 9 25]]

5. v.w = 219
   x.v =
 [29 77]
   x.y =
 [[19 22]
 [50 58]]

6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

   Concatenate v and w as rows:
 [[ 9 10]
 [11 12]]

7. x and v cannot concatenate because dimensions do not match.


In [ ]:
#Problem - 4: Matrix Operations:

#For the following arrays:
#x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
#v = np.array([9,10]) and w = np.array([11,12]);
#Complete all the task using numpy:

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#1)  A.A*−1 = I.
A_inv = np.linalg.inv(A)
print("1. A * A^-1:\n", np.dot(A, A_inv))

#2) AB ̸= BA.
AB = np.dot(A,B)
BA = np.dot(B,A)
print("\n2. AB:\n", AB)
print("\n   BA:\n", BA)
print("\n   Clearly AB != BA")

#3) (AB)T = BTAT
lhs = AB.T
rhs = np.dot(B.T , A.T)
print("\n3. (AB)^T:\n", lhs)
print("\n   B^T A^T:\n", rhs)







1. A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]

   BA:
 [[36 44]
 [13 16]]

   Clearly AB != BA

3. (AB)^T:
 [[23 51]
 [13 29]]

   B^T A^T:
 [[23 51]
 [13 29]]


In [ ]:
#Solve the following system of Linear equation using Inverse Methods.

#2x − 3y + z = −1
#x − y + 2z = −3
#3x + y − z = 9

C = np.array([
    [2, -3,  1],
    [1, -1,  2],
    [3,  1, -1]
])

D = np.array([-1, -3, 9])

C_inv = np.linalg.inv(C)
solution = np.dot(C_inv, D)

print("\nSolution using inverse:")
print("x =", solution[0])
print("y =", solution[1])
print("z =", solution[2])

solution2 = np.linalg.solve(C, D)
print("\nSolution using np.linalg.solve:\n", solution2)


Solution using inverse:
x = 2.0
y = 1.0
z = -2.0

Solution using np.linalg.solve:
 [ 2.  1. -2.]


In [ ]:
size = 1_000_000

# Python lists
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
print("\nList addition time:", time.time() - start, "seconds")

# NumPy
arr1 = np.arange(size)
arr2 = np.arange(size)

start = time.time()
arr_add = arr1 + arr2
print("NumPy addition time:", time.time() - start, "seconds")



# 2. Element-wise multiplication


start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
print("\nList multiplication time:", time.time() - start, "seconds")

start = time.time()
arr_mul = arr1 * arr2
print("NumPy multiplication time:", time.time() - start, "seconds")



# 3. Dot product


start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(size))
print("\nList dot product time:", time.time() - start, "seconds")

start = time.time()
dot_arr = np.dot(arr1,arr2)
print("NumPy dot product time:", time.time() - start, "seconds")


# 4. Matrix multiplication (1000x1000)

size_mat = 1000
A = np.random.random((size_mat,size_mat))
B = np.random.random((size_mat,size_mat))

# Python:
A_list = A.tolist()
B_list = B.tolist()

start = time.time()
C_list = [[sum(row[i] * col for i,col in enumerate(col_list))
            for col_list in zip(*B_list)]
          for row in A_list]
print("\nMatrix mult using lists:", time.time() - start, "seconds")

start = time.time()
C_np = np.dot(A,B)
print("Matrix mult using NumPy:", time.time() - start, "seconds")


List addition time: 0.13503313064575195 seconds
NumPy addition time: 0.005642414093017578 seconds

List multiplication time: 0.17615604400634766 seconds
NumPy multiplication time: 0.007124185562133789 seconds

List dot product time: 0.5561416149139404 seconds
NumPy dot product time: 0.0031964778900146484 seconds

Matrix mult using lists: 217.837322473526 seconds
Matrix mult using NumPy: 0.07234358787536621 seconds
